definitions:
  entity.LoginResponse:
    properties:
      token:
        $ref: '#/definitions/entity.TokenResponse'
      user:
        $ref: '#/definitions/entity.UserResponse'
    type: object
  entity.SimpleResponse:
    properties:
      data: {}
      message:
        description: Code    int         `json:"code"`
        type: string
    type: object
  entity.TokenResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  entity.UserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      role_id:
        type: string
      user_name:
        type: string
    type: object
  model.File:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      domain:
        description: save domain flexibly
        type: string
      file_name:
        type: string
      id:
        type: string
      path:
        type: string
      size:
        type: integer
      type:
        type: string
      updated_at:
        type: string
      updater_id:
        type: string
    type: object
  model.Post:
    properties:
      content:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      files:
        items:
          type: string
        type: array
      id:
        type: string
      image:
        type: string
      slug:
        type: string
      title:
        type: string
      updated_at:
        type: string
      updater_id:
        type: string
      user:
        $ref: '#/definitions/model.User'
      user_id:
        type: string
    type: object
  model.User:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      id:
        type: string
      password:
        type: string
      post:
        items:
          $ref: '#/definitions/model.Post'
        type: array
      social:
        type: string
      social_id:
        type: string
      updated_at:
        type: string
      updater_id:
        type: string
      user_name:
        type: string
    type: object
  request.CreatePostRequest:
    properties:
      content:
        type: string
      files:
        items:
          type: string
        type: array
      image:
        type: string
      slug:
        type: string
      title:
        type: string
    type: object
  request.GetListPostRequest:
    properties:
      limit:
        type: integer
      page:
        type: integer
      search:
        type: string
      sort:
        type: string
    type: object
  request.LoginRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 20
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  request.RegisterRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 20
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  request.UpdateFileRequest:
    properties:
      data:
        items:
          type: string
        type: array
      file_name:
        type: string
      id:
        type: string
    required:
    - id
    type: object
  request.UpdatePostRequest:
    properties:
      content:
        type: string
      files:
        items:
          type: string
        type: array
      id:
        type: string
      image:
        type: string
      slug:
        type: string
      title:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is Trial Backend API docs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Trial Backend API
  version: "2.0"
paths:
  /v1/api/auth/call-back:
    post:
      consumes:
      - application/json
      description: GoogleCallback
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: GoogleCallback
      tags:
      - Auth
  /v1/api/auth/google/login:
    post:
      consumes:
      - application/json
      description: GoogleLogin
      produces:
      - application/json
      responses:
        "302":
          description: Found
          schema:
            type: string
      summary: GoogleLogin
      tags:
      - Auth
  /v1/api/auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: LoginRequest
        in: body
        name: LoginRequest
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.LoginResponse'
      summary: Login
      tags:
      - Auth
  /v1/api/auth/register:
    post:
      consumes:
      - application/json
      description: Register
      parameters:
      - description: RegisterRequest
        in: body
        name: RegisterRequest
        required: true
        schema:
          $ref: '#/definitions/request.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Register
      tags:
      - Auth
  /v1/api/files:
    delete:
      consumes:
      - application/json
      description: Delete
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Delete
      tags:
      - File
    post:
      consumes:
      - multipart/form-data
      description: Upload
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: file_request
        in: formData
        name: file_request
        required: true
        type: file
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/model.File'
      summary: Upload
      tags:
      - File
    put:
      consumes:
      - multipart/form-data
      description: Update
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: UpdateFileRequest
        in: body
        name: UpdateFileRequest
        required: true
        schema:
          $ref: '#/definitions/request.UpdateFileRequest'
      - description: file_request
        in: formData
        name: file_request
        required: true
        type: file
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/model.File'
      summary: Update
      tags:
      - File
  /v1/api/files/{id}:
    get:
      consumes:
      - application/json
      description: GetOne
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/model.File'
      summary: GetOne
      tags:
      - File
  /v1/api/files/download/{id}:
    get:
      consumes:
      - application/json
      description: Download
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Download
      tags:
      - File
  /v1/api/health:
    get:
      consumes:
      - application/json
      description: Health
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Check health server
      tags:
      - Health
  /v1/api/image/upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: UploadFileRequest
        in: formData
        name: UploadFileRequest
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Upload
      tags:
      - Image
  /v1/api/posts:
    get:
      consumes:
      - application/json
      description: GetList
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: GetListPostRequest
        in: body
        name: GetListPostRequest
        required: true
        schema:
          $ref: '#/definitions/request.GetListPostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            items:
              $ref: '#/definitions/model.Post'
            type: array
      summary: GetList
      tags:
      - Post
    post:
      consumes:
      - application/json
      description: Create
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: CreatePostRequest
        in: body
        name: CreatePostRequest
        required: true
        schema:
          $ref: '#/definitions/request.CreatePostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/model.Post'
      summary: Create
      tags:
      - Post
    put:
      consumes:
      - application/json
      description: Update
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: UpdatePostRequest
        in: body
        name: UpdatePostRequest
        required: true
        schema:
          $ref: '#/definitions/request.UpdatePostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/model.Post'
      summary: Update
      tags:
      - Post
  /v1/api/posts/{id}:
    delete:
      consumes:
      - application/json
      description: Delete
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Delete
      tags:
      - Post
    get:
      consumes:
      - application/json
      description: GetOne
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/model.Post'
      summary: GetOne
      tags:
      - Post
  /v1/api/users:
    get:
      consumes:
      - application/json
      description: GetList
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
      summary: GetList
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/model.User'
      summary: Update
      tags:
      - User
  /v1/api/users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Delete
      tags:
      - User
    get:
      consumes:
      - application/json
      description: GetOne
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/model.User'
      summary: GetOne
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
