definitions:
  entity.LoginResponse:
    properties:
      token:
        $ref: '#/definitions/entity.TokenResponse'
      user:
        $ref: '#/definitions/entity.UserResponse'
    type: object
  entity.SimpleResponse:
    properties:
      domain: {}
      message:
        description: Code    int         `json:"code"`
        type: string
    type: object
  entity.TokenResponse:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      refresh_token:
        type: string
    type: object
  entity.UserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      role_id:
        type: string
      user_name:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is Trail Backend API docs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Trail Backend API
  version: "2.0"
paths:
  /v1/api/files:
    delete:
      consumes:
      - application/json
      description: Delete
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Delete
      tags:
      - File
    post:
      consumes:
      - application/json
      description: Upload
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Upload
      tags:
      - File
    put:
      consumes:
      - application/json
      description: Update
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Update
      tags:
      - File
  /v1/api/files/:id:
    get:
      consumes:
      - application/json
      description: GetOne
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: GetOne
      tags:
      - File
  /v1/api/files/download/:id:
    get:
      consumes:
      - application/json
      description: Download
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Download
      tags:
      - File
  /v1/api/health:
    get:
      consumes:
      - application/json
      description: Health
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Health
      tags:
      - Health
  /v1/api/image/upload:
    post:
      consumes:
      - application/json
      description: Upload
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Upload
      tags:
      - Image
  /v1/api/posts:
    get:
      consumes:
      - application/json
      description: GetList
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: GetList
      tags:
      - Post
    post:
      consumes:
      - application/json
      description: Create
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Create
      tags:
      - Post
    put:
      consumes:
      - application/json
      description: Update
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Update
      tags:
      - Post
  /v1/api/posts/:id:
    delete:
      consumes:
      - application/json
      description: Delete
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Delete
      tags:
      - Post
    get:
      consumes:
      - application/json
      description: GetOne
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: GetOne
      tags:
      - Post
  /v1/api/request/call-back:
    post:
      consumes:
      - application/json
      description: GoogleCallback
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: GoogleCallback
      tags:
      - Auth
  /v1/api/request/google/login:
    post:
      consumes:
      - application/json
      description: GoogleLogin
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Found
          schema:
            type: string
      summary: GoogleLogin
      tags:
      - Auth
  /v1/api/request/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.LoginResponse'
      summary: Login
      tags:
      - Auth
  /v1/api/request/register:
    post:
      consumes:
      - application/json
      description: Register
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Register
      tags:
      - Auth
  /v1/api/users:
    get:
      consumes:
      - application/json
      description: GetList
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: GetList
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Create
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Create
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Update
      tags:
      - User
  /v1/api/users/:id:
    delete:
      consumes:
      - application/json
      description: Delete
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: Delete
      tags:
      - User
    get:
      consumes:
      - application/json
      description: GetOne
      parameters:
      - description: authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.SimpleResponse'
      summary: GetOne
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
